// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"net/http"

	"github.com/RimuruChan/blueking-service-governance/bkms-server/pkg/infras/account/auth/backends"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthBackend creates a new instance of MockAuthBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthBackend {
	mock := &MockAuthBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthBackend is an autogenerated mock type for the AuthBackend type
type MockAuthBackend struct {
	mock.Mock
}

type MockAuthBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthBackend) EXPECT() *MockAuthBackend_Expecter {
	return &MockAuthBackend_Expecter{mock: &_m.Mock}
}

// GetLoginUrl provides a mock function for the type MockAuthBackend
func (_mock *MockAuthBackend) GetLoginUrl() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLoginUrl")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthBackend_GetLoginUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoginUrl'
type MockAuthBackend_GetLoginUrl_Call struct {
	*mock.Call
}

// GetLoginUrl is a helper method to define mock.On call
func (_e *MockAuthBackend_Expecter) GetLoginUrl() *MockAuthBackend_GetLoginUrl_Call {
	return &MockAuthBackend_GetLoginUrl_Call{Call: _e.mock.On("GetLoginUrl")}
}

func (_c *MockAuthBackend_GetLoginUrl_Call) Run(run func()) *MockAuthBackend_GetLoginUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthBackend_GetLoginUrl_Call) Return(s string) *MockAuthBackend_GetLoginUrl_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthBackend_GetLoginUrl_Call) RunAndReturn(run func() string) *MockAuthBackend_GetLoginUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCredential provides a mock function for the type MockAuthBackend
func (_mock *MockAuthBackend) GetUserCredential(request *http.Request) string {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCredential")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthBackend_GetUserCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCredential'
type MockAuthBackend_GetUserCredential_Call struct {
	*mock.Call
}

// GetUserCredential is a helper method to define mock.On call
//   - request *http.Request
func (_e *MockAuthBackend_Expecter) GetUserCredential(request interface{}) *MockAuthBackend_GetUserCredential_Call {
	return &MockAuthBackend_GetUserCredential_Call{Call: _e.mock.On("GetUserCredential", request)}
}

func (_c *MockAuthBackend_GetUserCredential_Call) Run(run func(request *http.Request)) *MockAuthBackend_GetUserCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthBackend_GetUserCredential_Call) Return(s string) *MockAuthBackend_GetUserCredential_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthBackend_GetUserCredential_Call) RunAndReturn(run func(request *http.Request) string) *MockAuthBackend_GetUserCredential_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockAuthBackend
func (_mock *MockAuthBackend) GetUserInfo(ctx context.Context, userCred string) (*backends.UserInfo, error) {
	ret := _mock.Called(ctx, userCred)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *backends.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*backends.UserInfo, error)); ok {
		return returnFunc(ctx, userCred)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *backends.UserInfo); ok {
		r0 = returnFunc(ctx, userCred)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backends.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userCred)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthBackend_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockAuthBackend_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userCred string
func (_e *MockAuthBackend_Expecter) GetUserInfo(ctx interface{}, userCred interface{}) *MockAuthBackend_GetUserInfo_Call {
	return &MockAuthBackend_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, userCred)}
}

func (_c *MockAuthBackend_GetUserInfo_Call) Run(run func(ctx context.Context, userCred string)) *MockAuthBackend_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthBackend_GetUserInfo_Call) Return(userInfo *backends.UserInfo, err error) *MockAuthBackend_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockAuthBackend_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, userCred string) (*backends.UserInfo, error)) *MockAuthBackend_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
